### PR TITLE
Import ratings file

### PR DESCRIPTION
**Pull request by davlin93**

### CODE REVIEW

**Comment by tonyjhuang** [comment]
looks good but fix the button display bug. Other than that good to go :+1:

**Comment by davlin93** [comment]
@tonyjhuang fixed display bug and added comments

**Comment by kehphin** [comment]
We need an additional document that instructs users how to format their csv data in order for it to be accurately parsed

**Comment by kehphin** [comment]
other than that, LGTM :ship:

**Comment by tonyjhuang** [comment]
+1 merge it! :100:

**Comment by tonyjhuang** [comment]
+1

**Pull request merged**
