### PR TITLE
fixed picture width regardless of group size, including unsorted group

### PR DESCRIPTION
**Pull request by kehphin**
screen shot 2015-04-03 at 3 47 59 pm
screen shot 2015-04-03 at 3 48 17 pm
screen shot 2015-04-03 at 3 48 51 pm
screen shot 2015-04-03 at 3 49 06 pm

### CODE REVIEW

**Comment by tonyjhuang** [comment]
are we allowing users to resize the window? if so, then agree with david, otherwise, im fine with fixed width

**Comment by kehphin** [comment]
so i was gonna do that, but then i thought of the fact that when you move a picture from groups of different widths i.e. unsorted to a group, the pictures will change sizes because its width is relative to their parent (the group div).. it would get pretty messy

**Comment by kehphin** [comment]
no we're not resizing the window

**Comment by davlin93** [comment]
this looks kinda awk to me
screen shot 2015-04-06 at 10 38 31 am

**Comment by davlin93** [comment]
what if we used sass to calc and store the px width of 50% of the group 1 box here and then set that as the width for all pics

**Comment by kehphin** [comment]
if the pictures arent centered, then the left and right margins of the pictures to the sides of the groups wont look the same and it doesnt look as clean

**Comment by kehphin** [comment]
what if we only had 1 group? then group 1 would take up the whole width of the app and the pictures would all be huge

**Comment by davlin93** [comment]
True... The model I initially had was for 1 group they took 25% and for 2+ they took 50% we can talk f2f in class

**Comment by kehphin** [comment]
p2p

**Comment by davlin93** [comment]
+1

**Comment by gary2546** [comment]
+1

**Pull request merged**
