### PR TITLE
add id to picture object

### PR DESCRIPTION
**Pull request by davlin93**

### CODE REVIEW

**Comment by tonyjhuang** [comment]
+1

**Comment by tonyjhuang** [comment]
-1 -1 -1

**Comment by tonyjhuang** [comment]
http://javascript.crockford.com/private.html 

this is a better pattern for incrementing index, rather than a globally available `id` var

**Comment by tonyjhuang** [comment]
```
var Picture = function(rating, filePath) {
    if(typeof Picture.idCounter === 'undefined') {
        Picture.idCounter = 0;
    }

    this.id = Picture.idCounter++;
    this.rating = rating;
    this.filePath = filePath;            
}
```

**Comment by kehphin** [comment]
+1

**Comment by tonyjhuang** [comment]
plas one

**Pull request merged**
